# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('config.json', '.'),
        ('app/styles.qss', 'app'),
    ],
    hiddenimports=[
        'PyQt6',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'PyQt6.QtNetwork',
        'PyQt6.QtPrintSupport',
        'PyQt6.QtXml',
        'PyQt6.sip',
        'openai',
        'docx',
        'docx.oxml',
        'docx.table',
        'docx.text',
        'pdfplumber',
        'pdfplumber.pdfpage',
        'pdfplumber.pdfparser',
        'markdown',
        'markdown.extensions',
        'requests',
        'pydantic',
        'pydantic_core',
        'pydantic.fields',
        'pydantic.models',
        'json',
        'json.decoder',
        'json.encoder',
        'os',
        'sys',
        'pathlib',
        'datetime',
        're',
        'base64',
        'urllib',
        'http',
        'ssl',
        'socket',
        'threading',
        'concurrent',
        'concurrent.futures',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'scipy',
        'PIL',
        'PIL.Image',
        'cv2',
        'torch',
        'tensorflow',
        'PySide6',
        'PySide2',
        'shiboken6',
        'shiboken2',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='简历优化助手_PyQt6版',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='简历优化助手_PyQt6版',
)
